apiVersion: apps/v1
kind: Deployment
metadata:
  name: adex-webapp-backend-deployment-dev
  namespace: adex-webapp-dev
  labels:
    app: adex-webapp-backend-label-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adex-webapp-backend-label-dev
  template:
    metadata:
      labels:
        app: adex-webapp-backend-label-dev
    spec:
      containers:
        - name: adex-webapp-backend-pod-dev
          image: bidahal/nodejs-back:dev
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m # this is the minimum cpu that this pod will use
              memory: 250Mi
            limits: # this is the limit on how much cpu can this pod use
              cpu: 1000m # this 'm' refers to the microns for cpu and 1000 microns = 1 cpu core and 'mi' refers to the megabit for the ram.
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: adex-webapp-backend-service-dev
  namespace: adex-webapp-dev
spec:
  type: NodePort
  selector:
    app: adex-webapp-backend-label-dev
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8080
      nodePort: 30202