apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: adex-webapp-backend-hpa
  namespace: adex-webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adex-webapp-backend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50